### ISSUE TITLE
ktl.core.timedPopup Not showing over a modal

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#104]
Hi Norm

I am using your timedPopup function but it doesn't show over a modal.  I have tested it by adding a class to it in ktl.js:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/c20c9825-e971-4dee-b8ea-00b57f489c9f)

Then I added a z-index of 2000:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/59cd6239-9def-4b7c-8f58-9d8a4e13c80f)

Would it be possible to either add a class to the popup so we can add our own z-index or could you change the z-index.

Craig

**Comment by CSWinnall** [comment]
Hi Norm

I've tried adding a z-index to the new class .timed-popup but I can't get it to take.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/128beb1e-739c-460b-8372-07033f10aa94)

The only way I have made it show is by editing the styles directly in the ktl.js

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/f0c03299-d9ff-4cda-977c-fcd21bc0004b)

Craig

**Comment by cortexrd** [comment]
You're right.  I've fixed this and improved it a bit at same time, to allow using your own style completely, as well as **custom status**, instead of being limited to **success**, **warning** and **error**.

Changed both timedPopup and infoPopup, so they work the same way.

Will be implemented in next release.  I need to fix a few other things before.  Should be tomorrow.

Norm

**Comment by CSWinnall** [comment]
Amazing as always

Craig

**Comment by cortexrd** [comment]
Released fix in v0.15.16.
Check all the other updates also that might interest you.
Dev popups are no fixed and won't scroll anymore.

**Comment by CSWinnall** [comment]
This is all excellent Norm.

One other thing if possible, could the user change the colours for:
Success
Warning
Error

So that they are more in line with their app?

Sorry I know these are minor things, but I can't see a way of changing those colours.

Craig

**Comment by cortexrd** [comment]
I agree, I've made this configurable and very flexible too.
See v0.15.18.

All you need to do is override this in your app:

```
ktl.core.setCfg({
    popupStyle: {
        //Override default styles here.
        success: ';background-color:#81b378;border:5px solid #294125',
        warning: ';background-color:#fffa5e;border:2px solid #7e8060',
        error: ';background-color:#FFB0B0;border:5px solid #660000',

        //Add you own custom styles here.
        critical: ';background-color:purple;color:yellow;border:2px solid #7e8060',
    },
})
```

Enjoy,
Norm

P.S. next time, create in issue please ;)

**Comment by CSWinnall** [comment]
Hi Norm

Thank you again.

I did not want to create a new issue as I felt it was part of the same
issue.  I will going forward.


Craig

**Comment by cortexrd** [comment]
Hi Craig,

I understand your point, but it's always better to have separate issues, even if related and seems like just a small update, because it's easier to track what's on my todo list.  Since this issue was closed a while ago, I had to scour for a while before I could find it.

Thanks again for your great collaboration.

Norm
