### ISSUE TITLE
Idea for bulk edit improvement - Reuse Last Source

### ISSUE THREAD

**Issue by cscott** [cortexrd/Knack-Toolkit-Library#13]
I like the idea behind the bulk edit feature, but it doesn't quite work for me: I want to list "unassigned" tasks, and then use bulk edit to assign a batch of them at once to a single user, but of course (and as noted in the docs) as soon as I assign my "example" task it disappears from the view so I can't use it to bulk edit the others.

I wonder if this could work slightly differently: if I create a "new record" form on my page *above* the grid that shows my query results, and "bulk edit" would take the field values from the form and apply them to the checked entries in the grid.  Perhaps you can hide or alter the behavior of the default "submit" button from the new record form to make that work.

**Comment by cscott** [comment]
That seems like it would work.  You'd do a 'normal' inline edit on the first row, and then click the 'select all rows' checkbox and 'apply last edit' and that would do the same thing to all the other selected rows.

**Comment by cortexrd** [comment]
Not exactly, but close.

Here's the typical sequence I'd see:

1) Click on all rows' checkboxes you wish to edit
2) Click on a columns to select the fields you wish to copy
3) Click on the source row to start the Bulk Edit process and wait until it completes

At that point I still have all the source data in memory, so I add that new button named **"Reuse Last Source"**

4) Repeat step 1) but with new records. Note that you can take all the time you need to apply various filters, sort, actually do anything **except refresh** the page.  The memory will retain your last source data.
5) Once your new row selection is satisfactory, click on the **"Reuse Last Source"** button instead of a source row.
6) The same changes will apply for the new section, and you can repeat this at will.

Norm

**Comment by cortexrd** [comment]
Dr. Scott,

I've taken the initiative to close the issue, since I didn't hear back from you.
Feel free to re-open it if you need anything else.

Norm
