### ISSUE TITLE
Feature turn off using the simple method is not working

### ISSUE THREAD

**Issue by godfredbrown** [cortexrd/Knack-Toolkit-Library#14]
Hi @cortexrd, the feature turn on and off using true or false, is not working.
I have turned off the features but it is still showing.
Could you please look at this asap.

**Comment by cortexrd** [comment]
Hi Godfred,

1) Thank you for using this page!
2) I just tested the procedure, and here everything works as expected - or should I say _STOPS_ working as expected!  All features are turned off, and I can enable them individually.

Here's what I see in my Tutorial app's Javascript pane:

![image](https://user-images.githubusercontent.com/42851359/230960154-9fb6f2ba-9c4e-4b56-888d-bace758db69f.png)

Can you validate that you have the same thing, and if not, send me your screen grab so I can inspect it please?

Normand

**Comment by godfredbrown** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/42617409/231028943-25f20b1b-5776-41c1-bce6-288146535628.png">

This is the image above. It goes on or off for the inline edit

**Comment by godfredbrown** [comment]
Alright Norman.
Looking forward to it

Thanks

**Comment by cortexrd** [comment]
Hi Godfred,

I think I've found the root cause of your problem.  Can you try this temporary "**dev**" code to see if it works for you please?
You must change **KTL_Start.js** to **KTL_Start-dev.js** as shown below.

![image](https://user-images.githubusercontent.com/42851359/232508207-80188966-d828-4e65-a05c-746cf04b9bfb.png)

If this works, I will migrate the changes to the official code.

Let me know,
Normand
