### ISSUE TITLE
Using bulk edit with filters/without visible source?

### ISSUE THREAD

**Issue by NaeJane** [cortexrd/Knack-Toolkit-Library#156]
Hi! TOTAL newbie with all this but directed here as I need a bulk edit function in my app...this could very well just be a user error on my part so I hope you can help!

The table I'm using requires filters, and I'm trying to bulk edit the field that is being filtered. So, when I edit the first line to use as the source, it disappears from the table so I can't use it. In the Demo 1 Youtube video, it showed you being able to select the required rows, inline edit one row, then apply the edit to all selected. However, since the feature update, this is no longer possible? And if I toggle the filters, I lose the selected rows, so it seems that there is no way to use the bulk edit option when filtering the table. This seems like a huge drawback, as the most obvious use of bulk edit would seem to be to filter the table to find and edit all the desired records that meet the criteria. Is there a way around this?! 

Thanks, Nae

**Comment by cortexrd** [comment]
Hi Nae,

You're right, the drawback if the 2nd version of that feature is that you must have a visible field that already has the value to be used as source.  The reason is that in the 1st version, I wasn't able to do multiple fields at once, which was even worse.  A lot of people need to be able to edit more than one field in a single operation.

But there's a solution!

1. Do a **_dummy_** Bulk Edit on a single row, that edits itself with the desired field(s).  I know this might seems senseless, but there's a reason: it stores the data in memory for the next steps.
2. You will now see a new button:  Reuse Last Source, disabled. Do not navigate away from the page, or you'll lose the stored data in memory.
3. Apply the filter you need to that same grid.  Adjust all you need, records per page, etc.
4. Select all records you need to affect with the checkboxes.  The top one in the header selects/deselects all.
5. Click on Reuse Last Source to start the process.

Enjoy,
Norm

**Comment by cortexrd** [comment]
Hi @NaeJane,

I know it's an old issue, but I've worked on this recently.  

You'll probably like the new method, where it's much simpler to do a natural "copy/paste" operation, like we've all been used to.

Switch to the **Beta** version and let me know it's more intuitive.
Note: The documentation is not yet updated, but will shortly.

Norm

**Comment by cortexrd** [comment]
Here's how it works.

Select a row, and optionally some columns (none=all), then click **Copy**.
The data will be copied to the KTL's dedicated clipboard, ready to be pasted to other records.

Next, you can filter or search whatever you need in that view and select (with the checkboxes) all the rows you want.

Click **Paste** and your data will be copied to all those rows, overwriting each respective field.

Trick: You can hover on the paste button's **eye icon** to see the content of the clipboard, if ever you need to remind yourself what was in there.

You can paste over and over, as many times as needed, as long as you don't refresh the page or navigate away.

Enjoy,
Norm
