### ISSUE TITLE
Post Error, Not Sure Why

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#157]
Hi Norm

We are using 18.9 when I click on a button to open a specific form I get this error:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/70bf91ab-c873-4f1e-8621-df49428aa713)

It doesn't seem to occur anywhere else (yet). When we open this form (same View) from somewhere else the error doesn't happen.

It points to this line of code:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/a9321ca9-3d80-43eb-b0fb-adbbddf7294f)

On this form we use your ktl.views.waitSubmitOutcome(viewId), I don't think this is causing it though.

Craig

**Comment by CSWinnall** [comment]
I bypassed the KTL and it didn't happen.
I went back to 18.2 it still happened
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/d5350ffe-8bbe-40f6-8da3-d1a4e65c3ec7)

**Comment by CSWinnall** [comment]
I can't really go back further than that due to other stuff breaking. This form is only a week old and we have never seen this before.

**Comment by CSWinnall** [comment]
use your normal login and go here
https://arcproject.knack.com/arc-beta#admissions/client-funders/care-managers/?view_4825_filters=%5B%5D
then click Add New Funder
Then Add New Care  Manager here:
![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/10554243/1c3163d5-982d-40c3-9ef4-74a4e428bab6)

Craig

**Comment by cortexrd** [comment]
I found the problem.

In your form, you have **4 primary buttons**. You must always have **only one** per form - the Submit button.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/90b09e26-fc45-400d-9126-842c1f4ac04f)

The code thinks that the first one is the Submit, so it submits the form when you click on it.

Then, since you have 3 **required** fields that are empty, the error 400 says "xyz are required."  You can see this if you examine the error's content as seen here:


![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/edf659ff-559d-4bd8-8fab-4f89f1c33d78)


So all you need to do is remove the ,is-primary class from the 3 buttons.

Norm

**Comment by CSWinnall** [comment]
Hi Norm

Thanks for looking into this for us.

 Ok we will remove this.  This is something we used to do and have since adopted for some unknown reason that we can't remember.  We have ended up using this across our app as we thought it provided the colour of the button.

Why doesn't it do it everywhere else including the other view which matched this one.  I'm not questioning the solution as this is an oversight on our part I'm just trying to understand as this was a convention we picked up 18 months ago when we didn't quite know as much as we do now.

Thanks for your time investigating this.

Craig

**Comment by cortexrd** [comment]
Your question is legitimate, indeed.  

But it's very hard to tell without in-depth investigation by comparing both forms side-by-side.  Maybe it's just because the fields in the other forms are not required?

If you need to keep the color, just add another class to the buttons and use CSS.  Ex: **.like-primary**

But for sure, having only one primary button is a good practice, and will solve the problem.

I will close this issue now, if you see something else, feel free to re-open.

Cheers,
Norm

**Comment by CSWinnall** [comment]
Ok thank you.
