### ISSUE TITLE
Blue Highlighting on Grids

### ISSUE THREAD

**Issue by AnthonyF96** [cortexrd/Knack-Toolkit-Library#173]
I have recently begun experiencing random blue highlighting across the grids. The issue goes away when I turn off KTL. I'm not sure if this is a config issue and I've done something incorrectly. Please see the example below. You'll note the left-hand side / right-hand side is grey/white and the center is blue.

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/154527313/0e61c2e8-ea6d-4a6d-9bee-03ee78686380)

**Comment by cortexrd** [comment]
Hi @AnthonyF96,

Good catch - thanks for reporting this.  I've fixed the bug and it will be available in next release.

FYI, the pale highlight is a KTL feature where the Inline-editable fields are subtly colorized to indicate they can be clicked.  Otherwise, you have to hover over each cell (column) to find out.

If you don't want that feature, you can turn it off completely.  You can also change the color to make it barely visible (more transparent) and matching your theme's color.

Normand

**Comment by AnthonyF96** [comment]
Thanks, Normand, that's great. I had a feeling it had something to do with this - however, we don't have in-line editing activated on most of our grids so I'd only seen it on one previously.

**Comment by cortexrd** [comment]
@AnthonyF96,

Can you confirm that we have a bug fix here please?
I would close this issue.

Thanks,
Norm
