### ISSUE TITLE
KTL error

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#177]
I am getting an error when loading the toolkit which is blocking my other javascript:
KTL_Defaults.js:253 KTL Setup error encountered:
 TypeError: Cannot read properties of null (reading 'addEventListener')
    at window.ktlReady (main.js?1703860459578&_=1703860459578:245:40)
    at KTL_Defaults.js:248:24
    at window.KnackApp (KTL_Defaults.js:255:7)
    at KTL_Start.js:83:25
    at n (k_98697145873cc4f2cf8d9e31a2917845cdac019c.js:961:1052366)
    at HTMLScriptElement.y (k_98697145873cc4f2cf8d9e31a2917845cdac019c.js:961:1052465)

**Comment by cortexrd** [comment]
Dean,

Can you send me the link to your app in a private message please?  No need to login or anything, just the link will do.

Norm

**Comment by cortexrd** [comment]
Hi Dean,

Thanks for sharing your app.

I found two problems:

1. The code block from line 245-276 inclusive are causing the problem you see.  The code is trying to attach event handlers to elements that don't yet exist.  Ex:  `document.getElementById('deleteLink').addEventListener('click', function (event) {...`    I will have to find a way to help users troubleshoot this in the future because indeed, it may seem like the KTL is causing this - but it's not.
2. Your API key is exposed, compromising your app's data security seriously.  To all people reading this... you should **NEVER** see this in your code: "**X-Knack-REST-API-Key**".  The API key must only be used on **server-side** code.  There's always a key-less solution to what you're trying to achieve.  From what I can see, you need to keep a timestamp of pages accessed by users.  Good news: the KTL provides an elegant solution that does just this and a lot more, if you're interested.

Normand

**Comment by djbbiz** [comment]
Hey Norm, thanks for catching that, I hadn't realized the API was exposed as we must have been testing internally and never went back and changed. Luckily this is an internal app only so limited users but I will go back and fix that. 

As for the code you believe to be the problem, it doesn't exist in my custom JavaScript, but more likely an external button that we are adding from another app's code. I will try eliminating that and see if it fixes the issue.

Thank you Norm - Dean

**Comment by cortexrd** [comment]
@djbbiz,

Let me know if I should close this issue, please.

Norm

**Comment by cortexrd** [comment]
Dean, I will close this now.  Feel free to re-open if needed.
