### ISSUE TITLE
Auto Focus fields - Default

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#18]
Hi Norm

Your auto focus seems to default to selecting the first text field it finds as we use quite a lot of other types this doesn't work for us.  We still would like to use this feature so turning it off would not be good.
Could you possibly make the default to do nothing or select the first field input it finds whether or not it's a text box.

This would be extremely useful as we use radio buttons a lot.

Update - Actually I'm not sure if this is an issue what do you think?

Craig

**Comment by CSWinnall** [comment]
Hi @cortexrd 

Sorry I've refined the problem a bit:
![image](https://user-images.githubusercontent.com/10554243/232048312-cba40a5d-f69e-48d0-8275-59a94184325d.png)


As you can see the second Input is the one selected. Again on this form:
![image](https://user-images.githubusercontent.com/10554243/232047875-c3baeea9-e2f7-46ae-9b34-d6858fad23b5.png)

Also if a radio button is selected it isn't displayed as selected:
![image](https://user-images.githubusercontent.com/10554243/232047512-aa9ca957-8e0d-4b2e-9751-bb6f3d0769fc.png)
Which means that you can't tell until you press a key which field you are changing.

I do realise that we could specify the field you would like selected but this seems a bit long winded.

Hope you can help

Craig

**Comment by cortexrd** [comment]
Hi Craig,

I had the same issue in another project.

Since you guys are using your own customized version the KTL_KnackApp.js file, you have full control of how you want autoFocus to behave.  There is already provision for what you need, an even more room for improvement.

Search for **function autoFocus()**

In there, you have this line:

`const autoFocusFields = [/*'field_xx', 'field_yy'*/]; //Add specific fields you want the focus on, if any.`

It allows you to specify an ordered list of fields on which to put focus, by priority from left to right.

If nothing is found, then the code below tries to search by field types in an order that I thought would be useful to most users.  But you can adapt it to your needs.

I like jQuery selectors because they never fail (crash).  In worst case, if no element is found, its length will be zero.  This is how you test for a found field by type or ID.


And here's another "demo" implementation I use in a specific project:

`function autoFocus() {
    if (window.self.frameElement //Never in iFrames.  Prevents parent from working properly.
        || curScn === 'scene_xxx' //Never in this scene...
        || curScn === 'scene_yyy' //... nor this one
    ) return;

    //These scenes do not work well with autofocus.
    //The best solution found was to blur the current object, otherwise the barcode scanner can only scan once.
    if (curScn === 'scene_zzz') {
        document.activeElement.blur();
        return;
    }

    const autoFocusFields = ['field_xxx', 'field_yyy'];

    var field = autoFocusFields.find(function (element) {
        if ($('#' + element).length > 0)
            return element;
    });

    if (field !== undefined) {
        $('#' + field).focus();
    } else {
        //This is another method to find an element by type, prioritizing from left to right.
        var field = document.querySelector('.kn-input-number input,.kn-input-short_text input,.kn-textarea,.table-keyword-search input');
        //Note:  Tried to include ".redactor-editor p" in that list above, but focus can't be set for some reason.

        if (field && !$(field).is(':offscreen')) { //Prevent annoying scroll if field is outside the view port.
            setTimeout(function () {
                field.focus();
            }, 500);
        }
    }
}
`

Hope this helps,
Norm

**Comment by CSWinnall** [comment]
Hi Norm

Thank you for that it was really helpful.

It might be worth mentioning in your readme that for selects to be selected they need to use 'view_xxx-field_yyy'.
I can't seem to get a radio button selected using its 'field_xxx' or its name in the **autoFocusFields**. Any ideas?

Also when the radio button is auto selected as default it isn't highlighted, is there a way to do this?

Craig

**Comment by cortexrd** [comment]
Here's an example on how to select a specific radio button option:

```
document.querySelector('#view_113 #kn-input-field_143 [value="Regular Price"').checked = true; //Plain Javascript.
$('#view_113 #kn-input-field_143 [value="On sale 25% off"')[0].checked = true; //jQuery.
```

I admit that to select a Dropdown Selector object, it's not like all other objects.  I might add that detail in my documentation.  But on the other hand, this is "Basic jQuery Selectors 101" knowledge, and I don't want to give a full course on that necessarily.  There's plenty of that stuff on Internet already and I need to concentrate on the KTL - there's already so much to say on this topic alone!

BTW, here's my _goto_ website for all my programming questions (selectors in this case):
[https://www.w3schools.com/jquery/jquery_ref_selectors.asp](url)

Norm

**Comment by CSWinnall** [comment]
Hi Thanks 
Again I really appreciate it

**Comment by CSWinnall** [comment]
I'm sorry if I didn't make myself clear but the issue was not about using Jquery selectors, while I appreciate the help, it was about the use of your auto focus function and how it doesn't seem to work with radio buttons or selects by just adding the 'field_xxx', as your suggestion describes in the knackApp code.  

While I understand why it doesn't work after looking at your code.  Other people may not and may spend an hour trying to figure it out.

Thank you for your time I do really appreciate it.

**Comment by cortexrd** [comment]
You know, when you have a satisfactory autoFocus function, I'd like to replace the KTL's default one by yours since it will reflect more use cases.

For my actual client, all forms look pretty much the same and this did the job so far.  But the fact that you guys have different needs is cool because your input brings a complement.

An idea I had would be to create some kind of a global keyword with parameters that would allow the users to determine the autoFocus function's behavior without having to code Javascript.

Food for thoughts...
Norm
