### ISSUE TITLE
Bulk Edit on View links from tables or Pivot Tables

### ISSUE THREAD

**Issue by rgolchin** [cortexrd/Knack-Toolkit-Library#193]
Thank you very much for this. This is amazing and very helpful. I have a question about the Bulk Edit. I noticed that that the Bulk Edit only shows up on the table on the main page after login. If we navigate to another view of that table with the same user that had the Bulk Edit role, the tables in the subsequent pages don't have that option. This is also true for pages that we navigate to from a Pivot table. I would appreciate hearing your thoughts on this. Thank you.

<img width="1683" alt="Screenshot 2024-01-16 at 10 45 43 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/43184950/39d860c2-7de9-4699-aba3-eacd2d24cb9a">
<img width="1636" alt="Screenshot 2024-01-16 at 10 46 34 AM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/43184950/ddc43123-2c55-436e-9158-8f35e8626de1">

**Comment by cortexrd** [comment]
@rgolchin,

Thanks for the nice comments :)

**Question**: are you using some **other keywords** in the view that doesn't have Bulk Edit and should?

Norm

**Comment by rgolchin** [comment]
Hello

In the main view that shows the bulk edit option I use the _ts and that is working fine. In the view that the bulk edit does not appear I am not using any keywords.

In general, to clarify, are you saying that the Bull Edit is a keyword? Just want to be sure I understand the concept of using it correctly.

Please let me know if you have any questions.


Rashid Golchin
Senior Consultant
Golchin Consulting Services
604-825-2875

On Jan 18, 2024, at 12:28 AM, Cortex R&D Inc. ***@***.***> wrote:

﻿

@rgolchin<https://github.com/rgolchin>,

Thanks for the nice comments :)

Question: are you using some other keywords in the view that doesn't have Bulk Edit and should?

Norm

**Comment by cortexrd** [comment]
No there is no keyword required for any Bulk Operations.  Except when you need to **disable** Bulk Ops for a specific view, then you'd use the _nbo keyword.  But that's not our case here.

I was asking because I've seen this problem where the Bulk Edit would be enabled, but it's when I use the _hc keyword in that grid.  Not sure why that is, I need to investigate more.

But in your case, it must some other issue.

Will keep you updated...
Norm

**Comment by rgolchin** [comment]
Ok, thank you. Looking forward to hearing from you. If you need any additional information please let me know.

**Comment by cortexrd** [comment]
Can you remove the Summary to see what happens please?

Does Bulk Edit come back?

Norm

**Comment by rgolchin** [comment]
Sorry just need a bit more clarification. When you say Summaty, are you referring to the second screenshot? And if so what part are you referring to?

**Comment by cortexrd** [comment]
Yes, the last line of your buggy grid:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/c7016411-b2df-4ff5-b298-d87d62ad4aee)

Disable Summary in the settgins to see what happens.

Norm

**Comment by rgolchin** [comment]
Yes that resolved the issue. I can see the Bulk Edit option now in the view table. Perfect. Now the natural question is, does the Bulk Edit not work with Table Summaries?

**Comment by cortexrd** [comment]
It very complicated!  

The relationship is as follows:

1. When Bulk Ops are enabled, the KTL add checkboxes in the first column
2. The Summary adds an extra row at the bottom of the table.  It may also add some additional rows if you want summaries per groups.
3. Since the Summaries are always added "later" - that's AFTER the view renders, all columns become mis-aligned in relationship to the rest of the table.
4. So we have to wait until the Summary finishes rendering before adding the Bulk checkboxes, to prevent this problem
5. But for some reason, in some cases, **we never get notified** that the Summary had finished rendering.
6. Furthermore, it seems that those renderings are somewhat random:  when we get them, we may have only one but once in a while, we see two or more, back to back.

So that's why the Bulk Ops seem broken.  All this because we can't tell when a Summary is done rendering.  I wish Knack could create a new event for us, just like these:  `$(document).on('knack-view-render.any'....`

But for Summaries like this for example:  `$(document).on('knack-view-render-summary.any'...`

Back to work...

Norm

**Comment by cortexrd** [comment]
I think I've got it fixed now.

Try **v0.22.6** please.

If you want, you can also try the **dev** version.  It shouldn't display the number info.  Just **KTL-dev**.

Norm

**Comment by rgolchin** [comment]
Thank you again. It works great now with the Summary view as well. Really appreciate your help.

Rashid

**Comment by cortexrd** [comment]
Thanks to you Rashid!!  You're helping us making the KTL better.

Spread the good news about the KTL in the Knack Forums.

Cheers,
Norm

**Comment by rgolchin** [comment]
Yes, absolutely will do. Thank you very much again.


Rashid Golchin
Senior Consultant
Golchin Consulting Services
604-825-2875

On Jan 18, 2024, at 2:17 PM, Cortex R&D Inc. ***@***.***> wrote:

﻿

Thanks to you Rashid!! You're helping us making the KTL better.

Spread the good news about the KTL in the Knack Forums.

Cheers,
Norm
