### ISSUE TITLE
Ive lost my popup debug box

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#201]
I lost the debug box that pops up when you click the KTL version in top right corner.  I accidentally dragged it so far to the left of the screen that it disappeared, and now I cant get it back.  is there a way to reset its location?  I've tried killing sessions, even restarting PC.  I'd like to avoid flushing the browser cache, unless that is the only way .... ?

**Comment by LeighBerrell** [comment]
I ended up clearing cache and it returned.  Please close.

**Comment by cortexrd** [comment]
Yeah, I know this is annoying, as it happened to me a few times.  Will soon add some code to auto-position the popup when out of scope.

It also happens when you open the browser's DevTools and it hides it.  Then you search for a while, only to realize it's a bit too far at the right, under the panel (when at right of course).

Like this:

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/42851359/cf877e43-5b5c-4427-a8d3-33b351ded58a)

Norm

**Comment by cortexrd** [comment]
@LeighBerrell,

This should be fixed now.  If you resize the app, the popups will auto re-center themselves and save the new position to avoid going off-limits.

You can test in dev.

Will be part of next release.

Norm
