### ISSUE TITLE
Delete Selected button shows up in the wrong spot

### ISSUE THREAD

**Issue by mitzvetsia** [cortexrd/Knack-Toolkit-Library#24]
You're going to get real sick of me... 

The "Delete Selected" Button is showing up at the top of the upper most table instead of at the top of the table it's applied to. 

![Screenshot 2023-05-18 at 3 39 10 PM](https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/c36f2f25-8682-48ad-8737-72422b3ed45e)

Page: https://scwinstallation.knack.com/installationservices#team-calendar/edit-client/64590a8037ed58002a158297/site-dashboard/64590ab073af1b002843d6a2/projects/64590ab073af1b002843d6a2/edit-client/64590a8037ed58002a158297/site-dashboard/64590ab073af1b002843d6a2/as-builts/64590ab073af1b002843d6a2/

The credentials I gave you for the bulk edit bug should still work for this page!

best,
Micah

**Comment by cortexrd** [comment]
Hi Micah,

"_You're going to get real sick of me..._"
- Absolutely not!  In fact, quite the opposite.  I really appreciate that you take the time to report the bugs and explain clearly what you see, vs what is expected, with screen grabs and all the good descriptions.  More people should copy you!

While replicating your problem, I found another one related to issue #15, when a grid has groupings.  But it's solved now and a fix will be available in next release.

Regarding you Delete bug in this post, I can't test it because I don't have the **Bulk Delete** role.  As soon as you add it, I'll be able to find the bug.  It should be easy.

Norm

**Comment by cortexrd** [comment]
No need for the Bulk Delete role finally.
I've finished the deployment of the bug fix.  Still in 0.11.12.  Just refresh your pages to see the effect.

Norm

**Comment by cortexrd** [comment]
Hi Micah,

Go read this post in the Discussions page:  [https://github.com/cortexrd/Knack-Toolkit-Library/discussions/35](url)
If you customized the KTL using a copy of the **KTL_KnackApp.js** file, it may affect you.  I can assist you in doing the transition.

Norm
nd@ctrnd.com
