### ISSUE TITLE
ToolKit Button conflict

### ISSUE THREAD

**Issue by djbbiz** [cortexrd/Knack-Toolkit-Library#26]
The Toolkit button in the header overlaps the mobile Hamburger Menu in the right-hand corner. It makes it harder to click the menu without accidentally clicking the Toolkit menu. I will probably use CSS to shut it off on mobile but you may want to consider a native solution.

**Comment by cortexrd** [comment]
Hi Dean,

The problem you're experiencing is due to the App's settings, in the Header & Page Menu / Use Legacy Design Settings set to **off**.

This enables the modern style, and as part of that, the hamburger menu is on the right instead of the left.

I think that what would be the best it to offer a system-wide set of options for the KTL, where such things could be configured easily.

One of those options would be 

- versionInfoBarDevOnly=[true,false]
- versionInfoBarX=[left,center,right]
- versionInfoBarY=[top,bottom]
- versionInfoBarOpacity=[0 to 100]

Do you think that would be good, and what else could we add?

Norm

**Comment by cortexrd** [comment]
Hi Dean,

I have added more controls for the version info bar, as mentioned above.
Go see this in the ktlCustomization.js file:

```
versionInfo: {
    viShowAppInfo: true,
    viShowKtlInfo: true,
    viShowToRoles: ['Developer'], //Add other roles who can see the version info bar.
    viPosX: 'right', //right, center, left
    viPosY: 'top', // top, bottom
    viPosXMobile: 'center',
    viPosYMobile: 'bottom',
    viOpacity: 50, //0 to 100 %
    viOpacityHover: 100, //0 to 100 %
},
```

Norm

**Comment by cortexrd** [comment]
Hi Dean,

Can you try the new flags and see if the improved version info bar solves the conflict you're having please?
If you have questions or need assistance, let me know.

Thanks,
Norm

**Comment by djbbiz** [comment]
All working well now.
