### ISSUE TITLE
Different name for "Account" object breaks user preferences

### ISSUE THREAD

**Issue by FBWSteve** [cortexrd/Knack-Toolkit-Library#27]
When installing KTL and trying to set up saved user preferences, nothing gets saved to the Knack database. I believe this is the case because in our instance of Knack, the Account object is actually named "Users", and the primary KTL.js file refers to it by the name "Accounts" specifically.

**Comment by FBWSteve** [comment]
Switching the object's name solves the issue.

**Comment by cortexrd** [comment]
Hi Steve,

I've modified the KTL structure so that it allows customizing the Accounts table to match your app's.  With this code below, you don't have to change your app to match KTL's requirements, but the other way around: KTL adapts to your app, just like any respectful toolkit should.

Add this to your Javascript pane in the Builder:

```
window.ktlReady = function () {
    //Put all your KTL-relatd code here: setup, callbacks, etc.
 
    ktl.iFrameWnd.setCfg({
        accountsObjName: 'Users' //Or any table name you have.
    });
}

```

Thanks,
Norm
