### ISSUE TITLE
Autofocus on 3rd field on form for some reason

### ISSUE THREAD

**Issue by LeighBerrell** [cortexrd/Knack-Toolkit-Library#279]
In the add form below, for some reason when KTL is running the form autofocuses on the third field on render, as shown.  I am using the minimal KTL startup, and there is nothing on this form to define the focus.  Doesnt happen if I disable KTL.  I've tested with current beta and still doing it with that.  Any idea why?   The only thing i can think of is that its because that is the first mandatory field?

![image](https://github.com/cortexrd/Knack-Toolkit-Library/assets/156155161/f79019f6-2908-4e63-8e54-16f130786926)

**Comment by chprojectsupport** [comment]
Hi Leigh,I’m a newbie to KTL and Norm recommended that I add KTL_Defaults.js. You add the code directly underneath the five lines of the loader. The “defaults” code allows you to customise your experience. Make sure any of your own custom code goes below the KTL_Defaults.js script as clearly shown: “//Your App-specific code goes here...”The code enables you to toggle lots of the prebaked options on/off by changing them to “false”. For instance, I don’t like to use the selTextOnFocus or the autoFocus, plus some others, so I switch them off. You can find the code folder here:cortexrd/Knack-Toolkit-Library: Knack Toolkit Librarygithub.comCarl HolmesOn 6 Apr 2024, at 07:25, LeighBerrell ***@***.***> wrote:﻿
In the add form below, for some reason when KTL is running the form autofocuses on the third field on render, as shown.  I am using the minimal KTL startup, and there is nothing on this form to define the focus.  Doesnt happen if I disable KTL.  I'ves tested with current beta and still doing it with that.  Any idea why?
image.png (view on web)

**Comment by cortexrd** [comment]
Hi @LeighBerrell,

Carl is right, the behavior is the default one, finding the first text input field in the form.  This was based on the requirements from my client Morbern since it saves a lot of time to the factory operators.

But pretty much everything is customizable in the KTL.

You can use this utility that I've created last week:  [KTL Configurator](https://github.com/cortexrd/Knack-Toolkit-Library/discussions/47#discussioncomment-8945131)

It contains all the flags and values that can be configured.
When you click on the question marks, it will open the linked documentation in a new tab.

Enjoy,
Norm

**Comment by cortexrd** [comment]
@chprojectsupport,

Actually, you are referring to the KTL_Customization.js file (not KTL_Defaults.js).

The procedure came from this page:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Customizing-Features

While this method will still work, it has become obsolete with the KTL Configurator, which makes the process much simpler.

Just as a clarification,
Norm

**Comment by LeighBerrell** [comment]
Thanks for that, I’ve used the configurator and now the autofocus is switched off.

 

But I now see something new which I hadn’t encountered before – on grid views there is now a small grey arrow at the left of each field title allowing that column to be collapsed.  Noice feature, but wondering which of the attributes turns it on or off?

 

Rgds

 

Leigh Berrell

0412 100 045

**Comment by cortexrd** [comment]
It is the **Global Hide/Show Columns** flag under the **Views** section.

You now have 3 options:

1. Go back to the Configurator to change the flag, save your config, regenerate your code and copy/paste it over the exiting code in the Builder.  A bit more work than necessary, but it's the basic method.

2. Use a simpler and quick method.  Go in the Builder and modify the flag directly:
**hscGlobal: true,**

Change true to **false**.

HSC stands for _Hide/Show Columns_.

This is simpler, but you become out of sync with your config file from the Configurator and your actual settings.  

So what I recommend is the third option: 

3. Change the flag manually in the Builder, then do the same change in your Configurator's settings and save it.  This is good because it both fast and synchronized.

Let me know if you have any questions.
Norm

**Comment by cortexrd** [comment]
Also, note that you can turn off the global flag and enable this feature per view, with the **_hsc** keyword.
https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Keywords#_hsc

Norm

**Comment by LeighBerrell** [comment]
Thanks, all good and fully understood.  Are you considering making the column hide/show settings persistent?  (similar to how you store user filters locally).   Might be a nice addition – would also be good to be able to drag columns around into the order the user wants and store that persistently too!

 

Rgds

 

Leigh Berrell

0412 100 045

**Comment by cortexrd** [comment]
>Are you considering making the column hide/show settings persistent?  (similar to how you store user filters locally).   Might be a nice addition 

That's exactly how it works actually!  The column's state are saved as part of your filters.  I just need to update the documentation to mention this.

>would also be good to be able to drag columns around into the order the user wants and store that persistently too!

That would be cool, but also quite complex for the near-term, but I'll keep it on the radar for future updates.
