### ISSUE TITLE
showappinfo window

### ISSUE THREAD

**Issue by garinfrost** [cortexrd/Knack-Toolkit-Library#32]
Dev/Prod button within the showappinfo window disabled if user is not "developerName".
showappinfo window always false unless user is in Developer group.

**Comment by cortexrd** [comment]
Hi Garin,

> Dev/Prod button within the showappinfo window disabled if user is not "developerName".

Yes, this is by design. Only the _Top Developer_ - the one with his name matches developerName - can enter Dev mode.  His development machine must have NodeJS installed and the file server running.  If someone without this setup could enter the Dev mode, the App will keep getting **file not found** error, until the cache is cleared.

> showappinfo window always false unless user is in Developer group.

The flag **showAppInfo** is actually independent of the user Role.  Maybe I didn't understand your issue?

Now as an improvement to this feature, there will be additional flags and control variables to determine how this **Version Info Bar** behaves.
See https://github.com/cortexrd/Knack-Toolkit-Library/issues/26#issuecomment-1566152716

Norm

**Comment by garinfrost** [comment]
It’s just looping:
“Updating app to new version, please wait…”


-----------------------------
Garin Frost
949-945-4064
***@***.***

**Comment by garinfrost** [comment]
I tested again this am and it is in fact looping:
“Updating app to new version, please wait…”


￼
-------------------------------------------------
Garin Frost
Frost Beer Works
(949) 945-4064
***@***.***
