### ISSUE TITLE
Persistence Forms in Grids when Editing Different records

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#326]
Hi Norm
There is an issue with persistent forms that if you are in a grid and you have an add form in a popup the persistence is carried over to different records here is a video of this happening:

https://www.loom.com/share/6f8c29f8f4354f0e927e08be62bb77b6?sid=31cbad1d-a225-461b-b058-c8dd13783deb

**Comment by cortexrd** [comment]
Craig,

You are right.  According to the documentation here:  https://github.com/cortexrd/Knack-Toolkit-Library/wiki/Features-Overview#form-persistence

_Data is erased when the form is submitted successfully, or user navigates away from page._

In a modal popup, closing the window without submitting and returning back to the parent page qualifies as "navigating away from the page".
So, I will fix that soon.

Norm

**Comment by cortexrd** [comment]
Craig,

I've released (and pushed) the Dev and Beta code with your fix for this bug.

FYI, I've decided to simply disable Persistent Forms for modal popups completely.  There's no added value for them anyways since they're supposed to be erased each time you close them.  So that's how they work now.

I'm closing this issue now.
Feel free to re-open it if you see anything else.

Thanks,
Norm
