### ISSUE TITLE
Persistent form

### ISSUE THREAD

**Issue by gstark1234** [cortexrd/Knack-Toolkit-Library#346]
I have this feature in my code, but it doesn't seem to be working. Here's a quick video: https://www.loom.com/share/9118c7eec39b484ab0f5d22083f2aeae?sid=1936a5ee-01db-4774-8ff4-4bcd9d06a035

**Comment by cortexrd** [comment]
Edit forms are not supported with Persistent Form.
Would be complicated to manage because after a refresh of the page (by example) it's not possible to know what is the original data vs the one modified by the user.  That would require a lot of work to compare the before vs after and colorize the changed fields.  So I decided to leave it out for now.

**Comment by cortexrd** [comment]
@gstark1234,

I will close this issue.  If ever you really need this feature, send me an email and we can discuss it.  
You just need to understand that implementing data persistence in Edit forms can cause some confusion.

One approach we have with large complex forms is to split them in several smaller ones, each with its own "subject" so to speak.  You can also put them in different page menus so it looks a bit like a Wizard flow (step-by-step).

Like this:

![image](https://github.com/user-attachments/assets/cebfb8b1-0c3b-4ca2-8d93-a0f7665d4dca)


Then these options:

![image](https://github.com/user-attachments/assets/81414fe2-a8da-4a1d-ac15-7d7debb779f1)


More settings:

![image](https://github.com/user-attachments/assets/cdfe35d6-b33d-420a-906c-ad50046ef75d)


So, you end up with an easy to navigate menu, like this:

![image](https://github.com/user-attachments/assets/38740359-5797-4c6d-948c-b856fad3918b)

Norm

**Comment by gstark1234** [comment]
Thanks, Norm!!
