### ISSUE TITLE
_ha on pivot tables

### ISSUE THREAD

**Issue by gstark1234** [cortexrd/Knack-Toolkit-Library#364]
Hi, Normand! Your video says that _ha applies to pivot reports. However, pivot reports don't have an area in the builder to specify the column alignment.  Can you give me more insight of how to apply this to pivot reports?

**Comment by cortexrd** [comment]
@gstark1234, 

You're right!  

Actually, there never was an option for column alignment.  The Pivot Tables' data was always right-aligned and left-aligned for the headers, which was inconsistent and bad looking.  That's why I had support for them with _ha.

But recently, Knack has fixed that and the _ha keyword is now obsolete for Pivot Tables.  With that fix, everything is always right-aligned and not configurable.

I will remove that from the documentation and the code.

Thanks for reporting,
Norm
