### ISSUE TITLE
Demo site for _afsg 

### ISSUE THREAD

**Issue by Max-Pigs** [cortexrd/Knack-Toolkit-Library#366]
I am having troubles figuring out how to get a drop down to change the connector record selector value in group 2. I wanted to look at the demo: https://ctrnd.knack.com/ktl-tutorials#auto-fill-and-submit-qr-generator/ but its requiring a user/PW. How do I get that?

Thanks!

**Comment by cortexrd** [comment]
Hi @Max-Pigs,

I've added the login information to that link you've been using.  Sorry about the omission!

Try again and use the provided demo account.

![image](https://github.com/user-attachments/assets/ac5d1ecd-5bf6-4e38-99c1-815882c0ef39)

If you have any additional question, let me know.
Norm

**Comment by Max-Pigs** [comment]
Thanks Norm!

I am a bit stumped with connected record selectors for asfg. I understand the idea of needing to get a record id, however I am struggling to get the record id into the text section of the selector in the keyword group. How can I make it dynamic based on selection of a drop down like you have in the demo? ktlTarget?

**Comment by cortexrd** [comment]
Hi @Max-Pigs,

I've tried to put myself back into context with this pretty complex feature, and to be honest, I was a bit lost at first in my own documentation!  So don't despair, it's not you :)

To help understanding, here are the screen grabs from the Builder, for the two pages...

1. To generate the QR Codes:

![image](https://github.com/user-attachments/assets/22435533-5d7f-44e8-8028-68a4f92c0933)


2. To read the QR code, auto-fill the form, then optionally submit and close:

![image](https://github.com/user-attachments/assets/32b14bf7-9b6d-41e7-953d-96e032a0b125)


As you can see, you don't need a record ID since the connected fields (source and destination) are in the same app.  By default, the _afsg keyword will handle it for you.

I was mentioning the record ID in the documentation to show how versatile this feature can be by sending QR Code across different tables or even different apps.  In such cases, since the QR generator can't know what's the foreign record ID, you must provide it manually and put in a text field that has the same name (label) as the destination's dropdown.  But that's pretty far fetch for now.

The important part is that the **field labels must match** in both views.

Go back to basics with the new information above, give it another try and let me know if it works.

Norm

**Comment by Max-Pigs** [comment]
Hey Norm!

No worries! I get it! 

This makes a bunch more sense already, I will give it a shot later today! 

Will report back!

**Comment by Max-Pigs** [comment]
Hey Norm! 

I have tried, and I have still come up short.....

I can get a QR code to show up, that will link me to the correct form. But I am not having luck with having it preselect options. I am noticing that if I select a different option there is no visual change to the QR code, which leads me to believe that it is not "updating", does it need a form submit to update the QR code? I cannot test this as I am also having issues getting bcg to work with URL fields on list views. See below for screen shot of the builder
![image](https://github.com/user-attachments/assets/b011c76e-b603-49fe-a2e7-3ca9bca25434)

Does _asfg need to be on the form that you wish to trigger? My understanding was that it could be for any other form fields matched up?

**Comment by Max-Pigs** [comment]
To follow up with a bit less tired brain, here is a bit more context on what I am trying todo:
I have two objects:

- Loaner Passes
- Loaner Pass Check outs

Each loaner pass checkout will have 1x loaner pass, each loaner pass can have multiple checkouts. 

I have 1x form to create new loaner passes. This adds a pass number (used to select the pass), and a pass id (which is similar to a CC number). 

I have another form that creates a new loaner pass checkout. You select the loaner pass, and then add relevant info such as person checking it out, checked out to, time of checkout ect. Every time a pass is checked out, you create a new loaner pass checkout and then check it back in. 

The goal would with _afsg would be to create a unique QR code for each loaner pass, that users can scan to quickly create a new loaner pass checkout. 

I have tried putting _afsg on both the form that creates new loaner passes (the url would point to the checkout form) or on the checkout form. Both would not work in creating a QR that takes me to the correct checkout form, but neither would autoselect the Loaner Pass Number.

Hope this gives a bit more context!

**Comment by cortexrd** [comment]
I'm getting most of it, but some parts are not 100% clear.

To save some time, would you like to have a zoom session with me live, so I can see your app and the builder?
I'm in Montreal, it's 10:15pm now.   I have a bit of time right now if that works with you.  If not, let me know when is the best time on your side.  You're in Seattle I think (7:15pm).

Norm

**Comment by Max-Pigs** [comment]
Happy too! 

I am running an errand right now. But should be back in the next 30-45m. If that’s toi late today just name a time.

**Comment by cortexrd** [comment]
No that's fine.  Send me the Zoom link at nd@ctrnd.com

**Comment by Max-Pigs** [comment]
Just sent you an invite.

**Comment by cortexrd** [comment]
@Max-Pigs,

I've modified the _afs/g feature to make it work properly.  It was a bad design in the first place because it uses Knack's default built-in method to populate the fields and this is done with the field IDs.

This didn't work in the cases where the field IDs are different in the generator page vs destination page - even if their labels were the same.

So now, I only rely on the labels instead of the IDs.  When I read the QR code, I use a function to trace back the field IDs based on the labels provided and this works as intended.

Give it a try in Dev mode.

If all ok, please close this issue.

Norm

**Comment by Max-Pigs** [comment]
Hey Norm! 

Just emailed you a bunch as well, but yes this works great in Dev mode! Just had to make sure the "reader" (aka my phone) was in dev mode too! Very powerful and awesome feature!
