### ISSUE TITLE
If server is not running return app to Prod Mode

### ISSUE THREAD

**Issue by CSWinnall** [cortexrd/Knack-Toolkit-Library#38]
Hi @cortexrd 

If possible when we first load the app can you check to see if the server is running.  If it isn't could you reload the page in prod mode?  It isn't a big issue I was trying to make a quick change to the app earlier and realised that the server was not running so I could not load the app.

Craig

**Comment by cortexrd** [comment]
I know!  I have this problem often, and tried to find a solution to it, without success.  There is no way (that I know of) to send a "test for server" query, in order to see if it's running or not.  All I get is a File Not Found error, but then my code can't trap it to switch to prod mode.

But I keep an eye on this, as maybe some day I'll find the trick.

Norm

**Comment by CSWinnall** [comment]
Hi Norm
I had a feeling that might be the case.  It isn't a big deal I will just have to remember it in future.  Having the local server is worth that problem as it far outweighs the alternative which is no server.

Craig

**Comment by cortexrd** [comment]
I will leave as Closed as Not Planned.  If ever I find a solution, I'll re-open and ask you to test it.
Norm
