### ISSUE TITLE
Arrays in keywords

### ISSUE THREAD

**Issue by amandajane-mo** [cortexrd/Knack-Toolkit-Library#46]
Hi Norm

Is there a way to use an array in keywords. e.g. _xx=field_yyy,[text1,text2]

I have tried to use the extractParamGroups but I think this is if you need to use multiple arrays like you _cfg keyword

Craig

**Comment by CSWinnall** [comment]
Hi Norm
I used the wrong browser sorry.
I have managed to use your extractParamGroups and only put [field_yyy,] in the first array.
This works

Thank you

**Comment by cortexrd** [comment]
Hi Craig,

Did you manage to implement your own keyword successfully?  I'm not sure if this issue is a question or just a comment...

FYI, the square bracket pairs must be used directly after the keyword's equal sign, like this:

**_keyword=[grp1_Param1, grp1_Param2, grp1_Param3], [grp2_Param1, grp2_Param2, grp2_Param3]**, etc.

Then, it's up to your code's parsing to know what each parameter inside each group does.
Then, since you fully control what's happening inside your keyword, you can even have "sub-keywords", giving you even more flexibility with the following parameter.  This can get pretty crazy!

Enjoy,
Norm

P.S. don't forget to close issues when done :)
