### ISSUE TITLE
Bulk Edit Not Working

### ISSUE THREAD

**Issue by mitzvetsia** [cortexrd/Knack-Toolkit-Library#65]
Hey Norm, 

Looks like something hinky has happened with one of the more recent updates perhaps and bulk edit / delete are not currently working. 

You can see the behavior the same place you logged in before: 

[Go here to login](https://scwinstallation.knack.com/installationservices#team-calendar/edit-client/64590a8037ed58002a158297/site-dashboard/64590ab073af1b002843d6a2/as-builts/64590ab073af1b002843d6a2/)

PW: %P&opn8@tx19

User Name: [nd@ctrnd.com](mailto:nd@ctrnd.com)

Maybe this helps with the bulk-edit issue: 

<img width="1494" alt="Screenshot 2023-07-02 at 11 17 22 PM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/d1955707-3801-49b7-ade2-5e4c0516c3a0">

I get the following message when attempting to use bulk delete: 

<img width="701" alt="Screenshot 2023-07-02 at 11 15 29 PM" src="https://github.com/cortexrd/Knack-Toolkit-Library/assets/35780481/96155449-0985-4abc-901f-c1bfd8772c64">

Thanks for your help!

-Micah

**Comment by cortexrd** [comment]
Hi Micah,

When you see error **403** and **Invalid token provided**, it means that your Knack login has expired and you need to logout then log back in to get rid of this.  Of course, this error also prevents all bulk operation from working properly.

But I've also fixed a few issues encountered while debugging your app.  I don't think they are related to your issue though.

This is what I'd ask you to do in the loader code:

1. Update your version to 0.13.14
2. Change from **min** to **full**.  This makes is a lot easier for me to debug in the future.  You won't notice any difference since loading takes a few tens of milliseconds.

Your code will look like this:

```
KnackInitAsync = function ($, callback) { // Load the Knack Toolkit Library (KTL)
    (window.LazyLoad = LazyLoad) && LazyLoad.js(['https://ctrnd.s3.amazonaws.com/Lib/KTL/KTL_Start.js'], () => {
        loadKtl($, callback, (typeof KnackApp === 'function' ? KnackApp : null), '0.13.14' /*KTL version, leave blank to get latest*/, 'full'/*min or full*/);
    })
};
```

Let me know this solves your problem and if you see any errors in the console output.

Norm

**Comment by mitzvetsia** [comment]
Done! And thanks for your quick work on this! The issue appears resolved. I don’t see any KTL related errors I the console.

Best!
Micah


Micah Shearer
Chief Operating Officer
T: 828-435-2790
***@***.***    |   W: www.getscw.com





My hours:  M-F 9 AM - 5 PM   EST

**Comment by cortexrd** [comment]
It's always a pleasure to see happy KTL users!
Thanks for reporting this issue,
Norm
